include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_new: false
    curly_braces_in_flow_control_structures: false

analyzer:
  exclude:
    - build/**
    - lib/generated/**
